### ISSUE TITLE
怎么设置半小时为基准，如下图

### ISSUE THREAD

**Issue by ISBN9527** [ozx174/time-period-selector#1]
![image](https://user-images.githubusercontent.com/30942709/123598306-f1156480-d826-11eb-9a1c-f1a7badbe526.png)

**Comment by ISBN9527** [comment]
@congbao1991

**Comment by congbao1991** [comment]
> @congbao1991

可以把源码先拷下来，拓展下格子数量就可以了。代码不复杂。  后面我有空就加个模式控制配置吧
